definitions:
  clients.AppError:
    properties:
      error_key:
        type: string
      log:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
  clients.SuccessRes:
    properties:
      data: {}
      filter: {}
      paging: {}
    type: object
  domain.ItemCreation:
    properties:
      description:
        type: string
      id:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  domain.ItemUpdate:
    properties:
      description:
        type: string
      status:
        $ref: '#/definitions/domain.Status'
      title:
        type: string
      updated_at:
        type: string
    type: object
  domain.Status:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Deleted
    - Active
    - Done
  domain.UserCreate:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  domain.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  domain.UserUpdate:
    properties:
      first_name:
        type: string
      last_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /items:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves a list of all items.
      produces:
      - application/json
      responses:
        "200":
          description: List of items retrieved successfully
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/clients.AppError'
      summary: Get all items
      tags:
      - Items
    post:
      consumes:
      - application/json
      description: This endpoint allows authenticated users to create an item.
      parameters:
      - description: Item creation payload
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/domain.ItemCreation'
      produces:
      - application/json
      responses:
        "200":
          description: Item successfully created
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/clients.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/clients.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/clients.AppError'
      summary: Create a new item
      tags:
      - Items
  /items/{id}:
    delete:
      consumes:
      - application/json
      description: This endpoint deletes an item identified by its unique ID.
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Item deleted successfully
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Invalid ID format or bad request
          schema:
            $ref: '#/definitions/clients.AppError'
        "404":
          description: Item not found
          schema:
            $ref: '#/definitions/clients.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/clients.AppError'
      summary: Delete an item
      tags:
      - Items
    get:
      consumes:
      - application/json
      description: This endpoint retrieves a single item by its unique identifier.
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Item retrieved successfully
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Invalid ID format or bad request
          schema:
            $ref: '#/definitions/clients.AppError'
        "404":
          description: Item not found
          schema:
            $ref: '#/definitions/clients.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/clients.AppError'
      summary: Get an item by ID
      tags:
      - Items
    put:
      consumes:
      - application/json
      description: This endpoint allows updating the properties of an existing item
        by its ID.
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      - description: Item update payload
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/domain.ItemUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Item updated successfully
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Invalid input or bad request
          schema:
            $ref: '#/definitions/clients.AppError'
        "404":
          description: Item not found
          schema:
            $ref: '#/definitions/clients.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/clients.AppError'
      summary: Update an item
      tags:
      - Items
  /users:
    patch:
      consumes:
      - application/json
      description: This endpoint logs a user into the system and returns a token.
      parameters:
      - description: User login payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Token successfully generated
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/clients.AppError'
      security:
      - BearerAuth: []
      summary: update user
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      description: This endpoint logs a user into the system and returns a token.
      parameters:
      - description: User login payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Token successfully generated
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/clients.AppError'
      summary: Login user
      tags:
      - Users
  /users/profile:
    get:
      consumes:
      - application/json
      description: Retrieve detailed information of a user based on their unique UUID.
      produces:
      - application/json
      responses:
        "200":
          description: User successfully retrieved
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Invalid user ID or user not found
          schema:
            $ref: '#/definitions/clients.AppError'
      security:
      - BearerAuth: []
      summary: Get user by ID
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: This endpoint registers a new user in the system.
      parameters:
      - description: User creation payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully registered
          schema:
            $ref: '#/definitions/clients.SuccessRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/clients.AppError'
      summary: Register a new user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
